version: '3.8'

services:
  backend:
    build: 
      context: ./backend

    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/.env
    depends_on:
      - db

  frontend:
    build: ./backend/frontend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/frontend/.env
    depends_on:
      - backend

  db:
    image: "postgres:15"
    env_file:
      - ./backend/backend/.env
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
